name: Run Jupyter Notebook and Generate HTML

on:
  push:
    branches:
      - python_

jobs:
  run_notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

            # Step 2: Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
    
      # Step 3: Install Maven
      - name: Install Maven
        run: sudo apt-get install -y maven

      # Step 4: Download Maven dependencies
      - name: Download Maven Dependencies
        run: mvn dependency:copy-dependencies -DoutputDirectory=libs

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter nbconvert kagglehub
          python kaggle_.py

      - name: Run Jupyter Notebook
        run: |
          cd execute
          jupyter nbconvert --to notebook --execute Gesture_Recognition_Project.ipynb --output executed_Gesture_Recognition_Project.ipynb
          cd ..

      - name: Convert Executed Notebook to HTML
        run: |
          cd execute
          jupyter nbconvert --to html executed_Gesture_Recognition_Project.ipynb --output executed_Gesture_Recognition_Project
          cd ..

      - name: List files
        run: ls -la  # Debugging step

      - name: Upload Notebook and HTML as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: executed_notebooks
          path: |
            execute/executed_Gesture_Recognition_Project.ipynb
            execute/executed_Gesture_Recognition_Project.html
