name: Run Jupyter Notebook, Generate HTML, and Release Artifacts

on:
  push:
    branches:
      - python_  # Trigger on pushes to the python_ branch

permissions:
  contents: write  # Required for creating releases and uploading assets

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install Maven
        run: sudo apt-get install -y maven

      - name: Download Maven Dependencies
        run: mvn dependency:copy-dependencies -DoutputDirectory=libs

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter nbconvert
      - name: Run scripts
        run: |
          python test.py
      - name: Run Jupyter Notebook
        run: |
          cd execute && mkdir outputs
          jupyter nbconvert --to notebook --execute notebook.ipynb --output outputs/executed_notebook.ipynb
          cd ..
      - name: Convert Executed Notebook to HTML
        run: |
          cd execute/outputs
          jupyter nbconvert --to html executed_notebook.ipynb --output executed_notebook
          cd ../..
      - name: List files
        run: ls -la  # Debugging step

      - name: Zip the execute folder
        run: |
          zip -r outputs.zip execute/outputs

      - name: Upload Zipped Folder as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: execute_folder
          path: outputs.zip

      # Create a GitHub release and attach artifacts to it
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Build ${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload Zipped Folder as Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: outputs.zip
          asset_name: outputs.zip
          asset_content_type: application/zip
