name: Rust CI/CD

# Trigger the workflow on push or pull_request events to the `main` branch
on:
    push:
      branches:
        - web_assembly_

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install C++ Compiler
        run: sudo apt-get install g++

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
         toolchain: stable  # Use the stable version of Rust

      # Step 3: Build the project
      - name: Build the project
        run: cargo build --release

      # Step 4: Run the project (this will print output to the Actions log)
      - name: Run the program
        run: cargo run      #  or cargo run --bin your_binary_name (cargo run --bin src/main.rs)
