name: Run Jupyter Notebook with IJava Kernel

on:
  push:
    branches:
      - python_  # Trigger the workflow on pushes to the 'main' branch

jobs:
  run_notebook:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Install Java, Maven, and Jupyter
      - name: Install Java, Maven, and Jupyter
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk maven  # Install Java 11 and Maven
          python3 -m pip install --upgrade pip
          pip install jupyter

      # Step 3: Download and Install the IJava Kernel
      - name: Install IJava Kernel
        run: |
          wget https://github.com/SpencerPark/IJava/releases/tag/v1.3.0/ijava-1.3.0.jar
          java -jar ijava-1.3.0.jar --install  # Install the IJava kernel
          jupyter kernelspec list  # Verify that the IJava kernel is installed

      # Step 4: Run the Jupyter Notebook
      - name: Execute Jupyter Notebook
        run: |
          jupyter nbconvert --to notebook --execute notebooks/example_notebook.ipynb --output notebooks/executed_notebook.ipynb

      # Step 5: Convert the Executed Notebook to HTML
      - name: Convert Executed Notebook to HTML
        run: |
          jupyter nbconvert --to html notebooks/executed_notebook.ipynb --output notebooks/executed_notebook.html

      # Step 6: List Files in the Notebooks Directory
      - name: List Files
        run: ls -la notebooks

      # Step 7: Upload Executed Notebook and HTML as Artifacts
      - name: Upload Notebook and HTML as Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: executed_notebooks
          path: |
            notebooks/executed_notebook.ipynb
            notebooks/executed_notebook.html
