name: Java CI

on:
  push:
    branches:
      - javac_  # Adjust the branch name as needed


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21' # Specify your Java version
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean install

      - name: Run Java Program
        run: cd execute_kotlin && mvn exec:java -Dexec.mainClass="KotlinInJava"