name: Run Jupyter Notebook with Java and Maven Dependencies

on:
  push:
    branches:
      - python_

jobs:
  run_notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Java and Jupyter
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-21-jdk maven
          pip install jupyter

      - name: Install IJava kernel
        run: |
          git clone https://github.com/SpencerPark/IJava.git
          cd IJava

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.9" # Quotes required to prevent YAML converting to number

      - name: Install gradle
        run: |
          gradle install

      - name: Run Jupyter Notebook
        run: |
          cd execute
          jupyter nbconvert --to notebook --execute notebook_java.ipynb --output executed_notebook_java.ipynb
          cd ..

      - name: Convert Executed Notebook to HTML
        run: |
          cd execute
          jupyter nbconvert --to html executed_notebook_java.ipynb --output executed_notebook_java
          cd ..

      - name: List files
        run: ls -la  # Debugging step

      - name: Upload Notebook and HTML as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: executed_notebooks
          path: |
            execute/executed_notebook_java.ipynb
            execute/executed_notebook_java.html
