name: Rust CI/CD

# Trigger the workflow on push or pull_request events to the `main` branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Rust environment
      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      # Step 3: Build the project
      - name: Build the project
        run: cargo build --release

      # Step 4: Run the project (this will print output to the Actions log)
      - name: Run the program
        run: cargo run      # or cargo run --bin your_binary_name (cargo run --bin src/main.rs)
