name: Run Jupyter Notebook with Java and Maven Dependencies

on:
  push:
    branches:
      - python_

jobs:
  run_notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Java and Jupyter
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-21-jdk maven
          pip install jupyter

      - name: Install IJava Kernel
        run: |
          mkdir -p ~/.local/share/jupyter/kernels/java
          curl -L https://github.com/SpencerPark/IJava/releases/latest/download/IJava-0.3.4.jar -o ~/.local/share/jupyter/kernels/java/IJava.jar
          echo -e "{\n  \"argv\": [\n    \"java\",\n    \"-jar\",\n    \"{path_to_IJava.jar}\",\n    \"-i\",\n    \"{connection_file}\"\n  ],\n  \"display_name\": \"Java\",\n  \"language\": \"java\"\n}" > ~/.local/share/jupyter/kernels/java/kernel.json

      - name: Run Jupyter Notebook
        run: |
          jupyter nbconvert --to notebook --execute notebook_java.ipynb --output executed_notebook_java.ipynb

      - name: Convert Executed Notebook to HTML
        run: |
          jupyter nbconvert --to html executed_notebook_java.ipynb --output executed_notebook_java

      - name: List files
        run: ls -la  # Debugging step

      - name: Upload Notebook and HTML as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: executed_notebooks
          path: |
            executed_notebook_java.ipynb
            executed_notebook_java.html
