name: Run In-Memory Java Code with Maven Dependencies

on:
  push:
    branches:
      - kotlin_

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      # Step 3: Install Maven to resolve dependencies
      - name: Install Maven
        run: sudo apt install -y maven

      # Step 4: Download Maven dependencies (e.g., commons-lang3)
      - name: Download Maven Dependencies
        run: |
          mkdir -p libs
          mvn dependency:copy-dependencies -DoutputDirectory=libs -DincludeScope=runtime

      # Step 5: Compile and run in-memory Java code with dependencies
      - name: Compile and Run In-Memory Java Code
        run: |
          # Write the Java code in memory
          JAVA_CODE=$(cat <<EOF
          import org.apache.commons.lang3.StringUtils;
          
          public class Hello {
              public static void greet() {
                  String message = "Hello from dynamically compiled Java!";
                  String capitalizedMessage = StringUtils.capitalize(message);
                  System.out.println(capitalizedMessage);
              }
          }
          EOF
          )

          # Save the Java code to a file
          echo "$JAVA_CODE" > Hello.java

          # Compile the in-memory Java code with downloaded dependencies
          javac -cp ".:libs/*" Hello.java

          # Run the compiled Java code
          java -cp ".:libs/*" Hello
