name: Run JShell with Maven Dependencies

on:
  push:
    branches:
      - kotlin_

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out code
        uses: actions/checkout@v2

      # Step 2: Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      # Step 3: Install Maven
      - name: Install Maven
        run: sudo apt-get install -y maven

      # Step 4: Download Maven dependencies
      - name: Download Maven Dependencies
        run: mvn dependency:copy-dependencies -DoutputDirectory=libs

      # Step 5: Run JShell with classes and print output at the end
      - name: Run JShell and Control Output
        run: |
          # Create and run the shell script to execute JShell with classes
          echo '#!/bin/bash
          mvn dependency:copy-dependencies -DoutputDirectory=libs
          jshell --class-path "libs/*" <<EOF
          
          import org.apache.commons.lang3.StringUtils;
          
          class MyGreeter {
              public static String greet(String name) {
                  String message = "hello there, " + name;
                  String capitalized = StringUtils.capitalize(message);
                  return capitalized;
              }
          }
          
          String result = MyGreeter.greet("world");
          System.out.println(result);
          
          EOF
          ' > run_jshell.sh
          chmod +x run_jshell.sh
          ./run_jshell.sh
