name: Double the Number Workflow

on:
  workflow_dispatch:
    inputs:
      number:
        description: 'Enter a number to double'
        required: true
        type: number

jobs:
  calculate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Calculate double the number using shell
      run: |
        # Get the user-provided number from input
        number=${{ github.event.inputs.number }}
        
        # Display the user-provided number
        echo "User provided number (Shell): $number"
        
        # Calculate double of the number using shell
        double_number=$(( number * 2 ))
        
        # Output the result using shell
        echo "Double of the number (Shell) is: $double_number"

