name: Double the Sum of Numbers Workflow

on:
  workflow_dispatch:
    inputs:
      numbers:
        description: 'Enter a list of numbers (one per line)'
        required: true
        type: string

jobs:
  calculate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Process numbers, sum and double using Python
      id: python_processing
      run: |
        # Get the user-provided numbers (newline-separated)
        numbers="${{ github.event.inputs.numbers }}"

        # Save the numbers to a temporary file for Python processing
        echo "$numbers" > numbers.txt

        # Run Python script to sum and double the sum
        python3 -c "
        # Python script to sum numbers and double the sum

        # Read the numbers from the file
        with open('numbers.txt', 'r') as file:
            numbers = [int(line.strip()) for line in file.readlines()]

        # Calculate the sum of the numbers
        sum_of_numbers = sum(numbers)

        # Double the sum
        doubled_sum = sum_of_numbers * 2

        # Print the results
        print(f'Sum of the numbers: {sum_of_numbers}')
        print(f'Doubled sum: {doubled_sum}')

        # Check if the doubled sum is even or odd
        if doubled_sum % 2 == 0:
            print('The doubled sum is even.')
        else:
            print('The doubled sum is odd.')
                "