name: Double the Number Workflow

on:
  workflow_dispatch:
    inputs:
      number:
        description: 'Enter a number to double'
        required: true
        type: number

jobs:
  calculate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Calculate double the number using shell
      run: |
        # Get the user-provided number from input
        number=${{ github.event.inputs.number }}
        
        # Display the user-provided number
        echo "User provided number (Shell): $number"
        
        # Calculate double of the number using shell
        double_number=$(( number * 2 ))
        
        # Output the result using shell
        echo "Double of the number (Shell) is: $double_number"

        # Set output variable to use in the next step
        echo "double_number=$double_number" >> $GITHUB_ENV

    - name: Run Python script to evaluate doubled number
      run: |
        # Get the doubled number from the previous step
        double_number=${{ env.double_number }}
        
        # Save a simple Python script that takes the doubled number
        echo "
        # Python script to evaluate the doubled number
        doubled_value = $double_number

        # Example evaluation: Print and check if the doubled value is even or odd
        print(f'Doubled value: {doubled_value}')
        if(doubled_value % 2 == 0):
          print('The doubled value is even.')
        else:
          print('The doubled value is odd.')
        " > evaluate_input.py
        
        # Run the Python script
        python3 evaluate_input.py
  